### ISSUE TITLE
Instantiating conflagration with no config list will result in an AttributeError

### ISSUE THREAD

**Issue by SovietPanda** [Machinarum/conflagration#4]
I want to be able to do something like this `cfg = api.conflagration(default_to_env=True)` in order to use a conflagration object that contains just environmental variables. But this will currently break on `files.extend(dir_files)` due to a NoneType object.

**Comment by SovietPanda** [comment]
It looks like `cfg = api.conflagration([], default_to_env=True)` will do what I want it to do but not sure if that's how you intended it to work.

**Comment by jidar** [comment]
Fixed in v.0.0.5

the files param now defaults to an empty list.
