### ISSUE TITLE
LowerCaseKeys overwrites duplicate namespaces rather than appending

### ISSUE THREAD

**Issue by dwalleck** [Machinarum/conflagration#8]
If dictionary passed into the __call__ method has keys that would collide once changed to lowercase, the value for the original key are discarded for the value from the newly lowercased key's values: https://github.com/Machinarum/conflagration/blob/master/conflagration/namespace.py#L55

Instead, the values should be merged. This code does not work since we are working with NamespaceDicts and not dictionaries, but is logically what I think should be happening:
```
class LowerCaseKeys(_BaseNamespaceModifier):
    """Automatically lowercases all keys in the original dictionary.
    """

    def __call__(self, original_dict):
        for k in original_dict.keys():
            if k.lower() != k:
                if k.lower() in original_dict:
                    original_dict[k.lower()].update(original_dict[k])
                else:
                    original_dict[k.lower()] = original_dict[k]
                del original_dict[k]
```

**Comment by jidar** [comment]
I may have fixed this with #11 , but I don't have a windows machine to test it on.
